import images from "./images"

const menu = [
  {
    id: 1,
    title: 'BananaNutsYogurt',
    category: 'Oats Meals',
    price: 10,
    img: images.BananaNutsYogurt,
  },
  {
    id: 2,
    title: 'BananaPancake',
    category: 'Pancakes',
    price: 10,
    img: images.BananaPancake,
  },
  {
    id: 3,
    title: 'BeansChicken',
    category: 'Main Course',
    price: 10,
    img: images.BeansChicken,
  },
  {
    id: 4,
    title: 'BoiledEgg',
    category: 'Eggs',
    price: 10,
    img: images.BoiledEgg,
  },
  {
    id: 5,
    title: 'BroccoliSalad',
    category: 'Salads',
    price: 10,
    img: images.BroccoliSalad,
  },
  {
    id: 6,
    title: 'ChickenRiceCake',
    category: 'Rice Cakes',
    price: 10,
    img: images.ChickenRiceCake,
  },
  {
    id: 7,
    title: 'ChocolateNutsYogurt',
    category: 'Oats Meals',
    price: 10,
    img: images.ChocolateNutsYogurt,
  },
  {
    id: 8,
    title: 'ChocolatePancake1',
    category: 'Pancakes',
    price: 10,
    img: images.ChocolatePancake1,
  },
  {
    id: 9,
    title: 'ChocolatePancake2',
    category: 'Pancakes',
    price: 10,
    img: images.ChocolatePancake2,
  },
  {
    id: 10,
    title: 'ChocolateRiceCake',
    category: 'Rice Cakes',
    price: 10,
    img: images.ChocolateRiceCake,
  },
  {
    id: 11,
    title: 'CornSalad',
    category: 'Salads',
    price: 10,
    img: images.CornSalad,
  },
  {
    id: 12,
    title: 'DarkOatsYogurt',
    category: 'Oats Meals',
    price: 10,
    img: images.DarkOatsYogurt,
  },
  {
    id: 13,
    title: 'FruitBowlHoney',
    category: 'Fruit Salads',
    price: 10,
    img: images.FruitBowlHoney,
  },
  {
    id: 14,
    title: 'FruitBowlSmoothie',
    category: 'Fruit Salads',
    price: 10,
    img: images.FruitBowlSmoothie,
  },
  {
    id: 15,
    title: 'FruitSalad1',
    category: 'Fruit Salads',
    price: 10,
    img: images.FruitSalad1,
  },
  {
    id: 16,
    title: 'FruitSalad2',
    category: 'Fruit Salads',
    price: 10,
    img: images.FruitSalad2,
  },
  {
    id: 17,
    title: 'FruitSalad3',
    category: 'Fruit Salads',
    price: 10,
    img: images.FruitSalad3,
  },
  {
    id: 18,
    title: 'FruitSalad4',
    category: 'Fruit Salads',
    price: 10,
    img: images.FruitSalad4,
  },
  {
    id: 19,
    title: 'FruitSalad5',
    category: 'Fruit Salads',
    price: 10,
    img: images.FruitSalad5,
  },
  {
    id: 20,
    title: 'FruitSalad6',
    category: 'Fruit Salads',
    price: 10,
    img: images.FruitSalad6,
  },
  {
    id: 21,
    title: 'GrapeJuice',
    category: 'Juices',
    price: 10,
    img: images.GrapeJuice,
  },
  {
    id: 22,
    title: 'GreenPeasPasta',
    category: 'Salads',
    price: 10,
    img: images.GreenPeasPasta,
  },
  {
    id: 23,
    title: 'MixedMeal1',
    category: 'Main Course',
    price: 10,
    img: images.MixedMeal1,
  },
  {
    id: 24,
    title: 'MixedMeals2',
    category: 'Main Course',
    price: 10,
    img: images.MixedMeals2,
  },
  {
    id: 25,
    title: 'NutsPancake',
    category: 'Pancakes',
    price: 10,
    img: images.NutsPancake,
  },
  {
    id: 26,
    title: 'NutsRiceCake',
    category: 'Rice Cakes',
    price: 10,
    img: images.NutsRiceCake,
  },
  {
    id: 27,
    title: 'OatsFruitAndNuts',
    category: 'Oats Meals',
    price: 10,
    img: images.OatsFruitAndNuts,
  },
  {
    id: 28,
    title: 'OatsKiwi',
    category: 'Oats Meals',
    price: 10,
    img: images.OatsKiwi,
  },
  {
    id: 29,
    title: 'OatsPeanutButterMuesli',
    category: 'Oats Meals',
    price: 10,
    img: images.OatsPeanutButterMuesli,
  },
  {
    id: 30,
    title: 'Omelette1',
    category: 'Eggs',
    price: 10,
    img: images.Omelette1,
  },
  {
    id: 31,
    title: 'Omelette2',
    category: 'Eggs',
    price: 10,
    img: images.Omelette2,
  },
  {
    id: 32,
    title: 'Omelette3',
    category: 'Eggs',
    price: 10,
    img: images.Omelette3,
  },
  {
    id: 33,
    title: 'PaneerBroccolliMeal',
    category: 'Main Course',
    price: 10,
    img: images.PaneerBroccolliMeal,
  },
  {
    id: 34,
    title: 'PaneerSalad',
    category: 'Salads',
    price: 10,
    img: images.PaneerSalad,
  },
  {
    id: 35,
    title: 'PeanutButterBananaRiceCake1',
    category: 'Rice Cakes',
    price: 10,
    img: images.PeanutButterBananaRiceCake1,
  },
  {
    id: 36,
    title: 'PeanutButterBananaRiceCake2',
    category: 'Rice Cakes',
    price: 10,
    img: images.PeanutButterBananaRiceCake2,
  },
  {
    id: 37,
    title: 'PeanutButterBananaToast',
    category: 'Rice Cakes',
    price: 10,
    img: images.PeanutButterBananaToast,
  },
  {
    id: 38,
    title: 'PineAppleGrilled',
    category: 'Fruit Salads',
    price: 10,
    img: images.PineAppleGrilled,
  },
  {
    id: 39,
    title: 'PineAppleJuice',
    category: 'Juices',
    price: 10,
    img: images.PineAppleJuice,
  },
  {
    id: 40,
    title: 'ProteinShake1',
    category: 'Supplements',
    price: 10,
    img: images.ProteinShake1,
  },
  {
    id: 41,
    title: 'RiceBroccoliChickenMeal1',
    category: 'Main Course',
    price: 10,
    img: images.RiceBroccoliChickenMeal1,
  },
  {
    id: 42,
    title: 'RiceBroccoliChickenMeal2',
    category: 'Main Course',
    price: 10,
    img: images.RiceBroccoliChickenMeal2,
  },
  {
    id: 43,
    title: 'RiceChickenMeal',
    category: 'Main Course',
    price: 10,
    img: images.RiceChickenMeal,
  },
  {
    id: 44,
    title: 'RiceSpinachEggMeal',
    category: 'Main Course',
    price: 10,
    img: images.RiceSpinachEggMeal,
  },
  {
    id: 45,
    title: 'SaucyPaneer',
    category: 'Salads',
    price: 10,
    img: images.SaucyPaneer,
  },
  {
    id: 46,
    title: 'ScrambledEggs1',
    category: 'Eggs',
    price: 10,
    img: images.ScrambledEggs1,
  },
  {
    id: 47,
    title: 'ScrambledEggs2',
    category: 'Eggs',
    price: 10,
    img: images.ScrambledEggs2,
  },
  {
    id: 48,
    title: 'ScrambledEggsToast',
    category: 'Eggs',
    price: 10,
    img: images.ScrambledEggsToast,
  },
  {
    id: 49,
    title: 'SpinachScrambledEggs',
    category: 'Eggs',
    price: 10,
    img: images.SpinachScrambledEggs,
  },
  {
    id: 50,
    title: 'SpinachScrambledEggsToast',
    category: 'Eggs',
    price: 10,
    img: images.SpinachScrambledEggsToast,
  },
  {
    id: 51,
    title: 'SproutedBeans',
    category: 'Salads',
    price: 10,
    img: images.SproutedBeans,
  },
  {
    id: 52,
    title: 'SunnySideUp',
    category: 'Eggs',
    price: 10,
    img: images.SunnySideUp,
  },
  {
    id: 53,
    title: 'VegSandwich1',
    category: 'Sandwiches',
    price: 10,
    img: images.VegSandwich1,
  },
  {
    id: 54,
    title: 'VegSandwich2',
    category: 'Sandwiches',
    price: 10,
    img: images.VegSandwich2,
  },
  {
    id: 55,
    title: 'VegSandwich3',
    category: 'Sandwiches',
    price: 10,
    img: images.VegSandwich3,
  },
  {
    id: 56,
    title: 'WaterMelonFetaSalad',
    category: 'Fruit Salads',
    price: 10,
    img: images.WaterMelonFetaSalad,
  },
  {
    id: 57,
    title: 'WatermelonJuice',
    category: 'Juices',
    price: 10,
    img: images.WatermelonJuice,
  },
  {
    id: 58,
    title: 'YogurtNutRiceCake',
    category: 'Rice Cakes',
    price: 10,
    img: images.YogurtNutRiceCake,
  },
  
]
export default menu
