const images = {
    BananaNutsYogurt: require("./Images/BananaNutsYogurt.jpg"),
    BananaPancake: require("./Images/BananaPancake.jpg"),      
    BeansChicken: require("./Images/BeansChicken.jpg"),        
    BoiledEgg: require("./Images/BoiledEgg.jpg"),
    BroccoliSalad: require("./Images/BroccoliSalad.jpg"),      
    ChickenRiceCake: require("./Images/ChickenRiceCake.jpg"),
    ChocolateNutsYogurt: require("./Images/ChocolateNutsYogurt.jpg"),
    ChocolatePancake1: require("./Images/ChocolatePancake1.jpg"),
    ChocolatePancake2: require("./Images/ChocolatePancake2.jpg"),
    ChocolateRiceCake: require("./Images/ChocolateRiceCake.jpg"),
    CornSalad: require("./Images/CornSalad.jpg"),
    DarkOatsYogurt: require("./Images/DarkOatsYogurt.jpg"),
    FruitBowlHoney: require("./Images/FruitBowlHoney.jpg"),
    FruitBowlSmoothie: require("./Images/FruitBowlSmoothie.jpg"),
    FruitSalad1: require("./Images/FruitSalad1.jpg"),
    FruitSalad2: require("./Images/FruitSalad2.jpg"),
    FruitSalad3: require("./Images/FruitSalad3.jpg"),
    FruitSalad4: require("./Images/FruitSalad4.jpg"),
    FruitSalad5: require("./Images/FruitSalad5.jpg"),
    FruitSalad6: require("./Images/FruitSalad6.jpg"),
    GrapeJuice: require("./Images/GrapeJuice.jpg"),
    GreenPeasPasta: require("./Images/GreenPeasPasta.jpg"),
    MixedMeal1: require("./Images/MixedMeal1.jpg"),
    MixedMeals2: require("./Images/MixedMeals2.jpg"),
    NutsPancake: require("./Images/NutsPancake.jpg"),
    NutsRiceCake: require("./Images/NutsRiceCake.jpg"),
    OatsFruitAndNuts: require("./Images/OatsFruitAndNuts.jpg"),
    OatsKiwi: require("./Images/OatsKiwi.jpg"),
    OatsPeanutButterMuesli: require("./Images/OatsPeanutButterMuesli.jpg"),
    Omelette1: require("./Images/Omelette1.jpg"),
    Omelette2: require("./Images/Omelette2.jpg"),
    Omelette3: require("./Images/Omelette3.jpg"),
    PaneerBroccolliMeal: require("./Images/PaneerBroccolliMeal.jpg"),
    PaneerSalad: require("./Images/PaneerSalad.jpg"),
    PeanutButterBananaRiceCake1: require("./Images/PeanutButterBananaRiceCake1.jpg"),      
    PeanutButterBananaRiceCake2: require("./Images/PeanutButterBananaRiceCake2.jpg"),      
    PeanutButterBananaToast: require("./Images/PeanutButterBananaToast.jpg"),
    PineAppleGrilled: require("./Images/PineAppleGrilled.jpg"),
    PineAppleJuice: require("./Images/PineAppleJuice.jpg"),
    ProteinShake1: require("./Images/ProteinShake1.jpg"),
    RiceBroccoliChickenMeal1: require("./Images/RiceBroccoliChickenMeal1.jpg"),
    RiceBroccoliChickenMeal2: require("./Images/RiceBroccoliChickenMeal2.jpg"),
    RiceChickenMeal: require("./Images/RiceChickenMeal.jpg"),
    RiceSpinachEggMeal: require("./Images/RiceSpinachEggMeal.jpg"),
    SaucyPaneer: require("./Images/SaucyPaneer.jpg"),
    ScrambledEggs1: require("./Images/ScrambledEggs1.jpg"),
    ScrambledEggs2: require("./Images/ScrambledEggs2.jpg"),
    ScrambledEggsToast: require("./Images/ScrambledEggsToast.jpg"),
    SpinachScrambledEggs: require("./Images/SpinachScrambledEggs.jpg"),
    SpinachScrambledEggsToast: require("./Images/SpinachScrambledEggsToast.jpg"),
    SproutedBeans: require("./Images/SproutedBeans.jpg"),
    SunnySideUp: require("./Images/SunnySideUp.jpg"),
    VegSandwich1: require("./Images/VegSandwich1.jpg"),
    VegSandwich2: require("./Images/VegSandwich2.jpg"),
    VegSandwich3: require("./Images/VegSandwich3.jpg"),
    WaterMelonFetaSalad: require("./Images/WaterMelonFetaSalad.jpg"),
    WatermelonJuice: require("./Images/WatermelonJuice.jpg"),
    YogurtNutRiceCake: require("./Images/YogurtNutRiceCake.jpg"),
}

export default images


    